apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: colossal-kingfisher-python 
  janus-idp.io/tekton: colossal-kingfisher-python
  backstage.io/kubernetes-id: colossal-kingfisher-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: colossal-kingfisher-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  