apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: colossal-kingfisher-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: colossal-kingfisher-python 
  name: colossal-kingfisher-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: colossal-kingfisher-python 
